services:
  postgres:
    container_name: postgres-qtim
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: qtim
      POSTGRES_PASSWORD: qtim
      POSTGRES_DB: qtim
    volumes:
      - ./postgres-data:/var/lib/data/postgres
  redis:
    container_name: redis-qtim
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

    volumes:
      - ./redis-data:/var/lib/data/redis

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:
  redis_data:
